os: linux
language: python
python:
- 2.6
- 2.7
- 3.4
- 3.5
- 3.6
- pypy
- pypy3
matrix:
  include:
    - python: 3.7
      dist: xenial
      # TODO: remove this hack once it's not required any more
      sudo: true
    - os: osx
      # Not required but makes Travis' output prettier
      python: 2.7
      language: generic
      env: MB_PYTHON_VERSION=2.7
    - os: osx
      python: 3.4
      language: generic
      env: MB_PYTHON_VERSION=3.4
    - os: osx
      python: 3.5
      language: generic
      env: MB_PYTHON_VERSION=3.5
    - os: osx
      python: 3.6
      language: generic
      env: MB_PYTHON_VERSION=3.6
    - os: osx
      python: 3.7
      language: generic
      env: MB_PYTHON_VERSION=3.7
before_install: |
  if [ $TRAVIS_OS_NAME == osx ]; then
    git clone https://github.com/matthew-brett/multibuild
    touch config.sh # required by the multibuild project
    source multibuild/common_utils.sh
    source multibuild/travis_steps.sh
    before_install
  fi
install: |
  pip install pytest pytest-runner setuptools_scm
script: |
  MEDIAINFO_BUNDLE=1 python setup.py build
  python setup.py test
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  skip_upload_docs: true
  provider: pypi
  user: sbraz
  password:
    secure: PPuAhhXw9Ccs0ydbCSaEwocIzIDN6YrT0pWA9HHIBD2NVSFcgr0TBS/D0g2xUOCJtrXt4VlMYmgNop8vA/JjgiRWze6t1SPAKawbHqmVtCUORqqxWOWxXSh330LgWZyXnpsGpAyWSozG7cwJ3AGNsGfmxs8las4qgSWG5o9v/mA=
  on:
    branch: master
    tags: true
    python: 3.6
