name: Build & upload PyPI package

on:
  release:
    types:
      - published
  workflow_dispatch:

env:
  dists-artifact-name: python-package-distributions

jobs:
  build-wheels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
      - name: Install dependencies
        run: pdm install --dev --no-self
      - name: Build the bundled wheels
        run: pdm run build_all
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.dists-artifact-name }}
          path: dist/*


  # Upload to Test PyPI manually triggered.
  release-test-pypi:
    name: Publish in-dev package to test.pypi.org
    environment: release-test-pypi
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build-wheels
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.dists-artifact-name }}
          path: dist/
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true
          repository-url: https://test.pypi.org/legacy/


  # Upload to real PyPI on GitHub Releases.
  release-pypi:
    name: Publish to PyPI
    needs: build-wheels
    environment: release-pypi
    if: github.repository_owner == 'sbraz' && github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.dists-artifact-name }}
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true
